import project from './project'
import post from './post'
import homePage from './homePage'
import aboutPage from './aboutPage'
import contactPage from './contactPage'
import siteSettings from './siteSettings'
import designSystem from './designSystem'
import blogPage from './blogPage'
import servicesPage from './servicesPage'
import projectsPage from './projectsPage'
import legalPage from './legalPage'
import testimonial from './testimonial'
import processStep from './processStep'
import service from './service'
import community from './community'
import category from './category'
import { accessibleImage } from './accessibleImage'
import { seo } from './seo'

export const schemaTypes = [project, post, homePage, aboutPage, contactPage, siteSettings, designSystem, blogPage, servicesPage, projectsPage, legalPage, testimonial, processStep, service, community, category, accessibleImage, seo]
